version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - '${DB_PORT:-5432}:5432'
    networks:
      - api
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis
    ports:
      - ${REDIS_PORT:-0}:6379
    networks:
      - api
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.10.0
    ports:
      - ${AZURE_BLOB_PORT:-10000}:10000
    volumes:
      - azurite_data:/opt/azurite/folder
    environment:
      executable: blob
    networks:
      - api
    command: azurite-blob -l /data --blobHost 0.0.0.0 -d /data/debug.log --loose


volumes:
  rubygems_cache:
  azurite_data:
networks:
  api:
