version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - '${DB_PORT:-0}:5432'
    networks:
      - api
  redis:
    image: redis
    ports:
      - ${REDIS_PORT:-0}:6379
    networks:
      - api
  minio:
    image: minio/minio:RELEASE.2018-08-25T01-56-38Z
    volumes:
      - minio_data:/export
    ports:
      - ${S3_PORT:-0}:9000
    environment:
      MINIO_ACCESS_KEY: accessKey1
      MINIO_SECRET_KEY: verySecretKey1
    command: server minio_data


volumes:
  rubygems_cache:
  minio_data:
networks:
  api:
