version: '3'
services:
  dev:
    build:
      context: .
    links:
      - db
    environment:
      RAILS_ENV:
      DB_HOST: db
      DB_USERNAME: postgres
      BUNDLE_WITHOUT: production
    volumes:
      - ../..:/app
      - rubygems_cache:/usr/local/bundle

  db:
    image: postgres:9.3.5
    ports:
      - '${DB_PORT:-5432}:5432'

volumes:
  rubygems_cache:
