version: '3'
services:
  dev:
    build:
      context: .
    links:
      - db
    environment:
      RAILS_ENV:
      DB_HOST: db
      DB_USERNAME: postgres
      BUNDLE_WITHOUT: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 1
      S3_DIRECT_UPLOAD_BUCKET: 'etapidirectbucket'

    volumes:
      - ../..:/app
      - rubygems_cache:/usr/local/bundle
    ports:
      - ${PORT:-0}:8080
    networks:
      - api

  db:
    image: postgres:9.3.5
    ports:
      - '${DB_PORT:-0}:5432'
    networks:
      - api
  redis:
    image: redis
    ports:
      - ${REDIS_PORT:-0}:6379
    networks:
      - api
  s3_mock:
    image: scality/s3server
    networks:
      api:
        aliases:
          - "s3.docker.test"
    ports:
      - "${S3_PORT:-0}:8000"
volumes:
  rubygems_cache:
networks:
  api:
