version: '3'
services:
  dev:
    build:
      context: .
    links:
      - db
      - azurite
      - redis
    environment:
      RAILS_ENV:
      DB_HOST: db
      DB_USERNAME: postgres
      BUNDLE_WITHOUT: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 1
      AZURE_STORAGE_BLOB_HOST: http://azurite:10000
      AZURE_STORAGE_BLOB_FORCE_PATH_STYLE: 'true'
      AZURE_STORAGE_ACCOUNT: devstoreaccount1
      AZURE_STORAGE_ACCESS_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      AZURE_STORAGE_CONTAINER: et-api-test-container
      AZURE_STORAGE_DIRECT_UPLOAD_ACCOUNT: devstoreaccount1
      AZURE_STORAGE_DIRECT_UPLOAD_ACCESS_KEY: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
      AZURE_STORAGE_DIRECT_UPLOAD_CONTAINER: et-api-direct-test-container

    volumes:
      - ../..:/home/app/et-api
      - rubygems_cache:/usr/local/bundle
    ports:
      - ${PORT:-0}:8080
    networks:
      - api
