version: '3'
services:
  dev:
    build:
      context: .
    links:
      - db
    environment:
      RAILS_ENV:
      DB_HOST: db
      DB_USERNAME: postgres
      BUNDLE_WITHOUT: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 1
    volumes:
      - ../..:/app
      - rubygems_cache:/usr/local/bundle
    ports:
      - ${PORT:-0}:8080

  db:
    image: postgres:9.3.5
    ports:
      - '${DB_PORT:-0}:5432'
  redis:
    image: redis
    ports:
      - ${REDIS_PORT:-0}:6379

volumes:
  rubygems_cache:
