version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: sidekiq
    versions:
    - 6.1.3
    - 6.2.0
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 5.0.0
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: rails
    versions:
    - 6.1.3
  - dependency-name: simplecov
    versions:
    - 0.21.2
  - dependency-name: nokogiri
    versions:
    - 1.11.1
  - dependency-name: iodine
    versions:
    - 0.7.43
  - dependency-name: dotenv-rails
    versions:
    - 2.7.6
  - dependency-name: site_prism
    versions:
    - "3.7"
  - dependency-name: rubocop-rspec
    versions:
    - 1.41.0
  - dependency-name: factory_bot
    versions:
    - 6.1.0
