language: ruby
sudo: false
cache:
  bundler: true
  directories:
      - tmp/parallel_runtime_log
services:
  - postgresql
addons:
  postgresql: '9.5'
env:
  global:
    - ENABLE_COVERAGE=true
    - DB_USERNAME=postgres
before_install:
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter"
before_script:
  - bundle install && bundle exec db:create db:migrate RAILS_ENV=test
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
- bundle exec rspec
after_success:
- bundle exec codeclimate-test-reporter
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT