export_claims_job:
  cron: "*/<%= ENV.fetch('EXPORT_CLAIMS_EVERY', '15') %> * * * *"
  class: "ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper"
  description: "ClaimsExportJob"
  args:
    -
      job_class: EtAtosExport::ClaimsExportJob
      arguments:
        -
